I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 120, in script
    return
Exception: Could not find return label (u'C:\\Users\\Switch\\Desktop\\Games\\renpy-6.99.12.4-sdk\\Test/game/script.rpy', 1515444086, 49, 'end_translate').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 120, in script
    return
  File "C:\Users\Switch\Desktop\Games\renpy-6.99.12.4-sdk\renpy\ast.py", line 1400, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Switch\Desktop\Games\renpy-6.99.12.4-sdk\renpy\execution.py", line 586, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'C:\\Users\\Switch\\Desktop\\Games\\renpy-6.99.12.4-sdk\\Test/game/script.rpy', 1515444086, 49, 'end_translate').

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Test 1.0
